# run on container environment
sudo: required

language: php

cache:
  directories:
    - node_modules

php:
  - '5.6'
  
env:
  matrix:
    # nightly:
    - WP_VERSION=4.4 
  global:
    - WP_CORE_DIR=/home/www/wordpress
    - WP_TESTS_DIR=/home/www/wordpress-tests-lib
    - DB_NAME=wordpress_test
    - DB_USER=root
    - DB_PASSWORD=''
    - WP_MULTISITE=0
before_install:
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN --no-interaction
  - 'echo "{ \"token\": \"${GITHUB_OAUTH_TOKEN}\"}" >> frontend/.tsdrc'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - composer install -d ./plugins/versionpress
  - nvm install node
  - npm install
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo a2enmod rewrite
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - bash build/install-wp-tests.sh $DB_NAME $DB_USER "$DB_PASSWORD" localhost $WP_VERSION 
  - npm install -g gulp
  - npm install gulp
  - cp plugins/versionpress/tests/test-config.sample.yml plugins/versionpress/tests/test-config.yml
  
  - 'sed -i.bak -e "s/end2end-test-type: .*/end2end-test-type: wp-cli/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s/dbname: .*/dbname: $DB_NAME/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s/user: .*/user: $DB_USER/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s/password: .*/password: $DB_PASSWORD/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s#path: .*#path: $WP_CORE_DIR#" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s#url: .*#url: http://localhost/wordpress#" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s#firefox-binary: .*#firefox-binary: /usr/local/bin/firefox#" plugins/versionpress/tests/test-config.yml'

script: gulp --cwd plugins/versionpress/tests run-tests