# run on container environment
sudo: required

language: php

services:
  - mysql

cache:
  directories:
    - node_modules
    - plugins/versionpress/vendor

php:
  - '5.6'
  
env:
  matrix:
    # nightly:
    - WP_VERSION=4.4 
  global:
    - WP_CORE_DIR=/tmp/wordpress
    - WP_TESTS_DIR=/tmp/wordpress-tests-lib
    - DB_NAME=wordpress_test
    - DB_USER=root
    - DB_PASSWORD=''
    - DB=mysql
before_install:
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN --no-interaction
  - 'echo "{ \"token\": \"${GITHUB_OAUTH_TOKEN}\"}" >> frontend/.tsdrc'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - nvm install node
  - npm install
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot;
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - wp core download --path=$WP_CORE_DIR
  - wp core config --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASSWORD --dbhost=localhost --path=$WP_CORE_DIR --skip-check
  - wp core install --url="http://localhost/wordpress" --title="Title" --admin_user="admin" --admin_password="admin" --admin_email="admin@domain.com" --path=$WP_CORE_DIR
  - npm install -g gulp
  - cp plugins/versionpress/tests/test-config.sample.yml plugins/versionpress/tests/test-config.yml
  - mkdir -p $WP_CORE_DIR/wp-content/plugins/versionpress/src/
  - cp -rip plugins/versionpress/src/ $WP_CORE_DIR/wp-content/plugins/versionpress/src/
  - cp -rip plugins/versionpress/admin/ $WP_CORE_DIR/wp-content/plugins/versionpress/admin/
  - cp -rip plugins/versionpress/temp/ $WP_CORE_DIR/wp-content/plugins/versionpress/temp/
  - cp -rip plugins/versionpress/log/ $WP_CORE_DIR/wp-content/plugins/versionpress/log/
  - cp -rip plugins/versionpress/vendor/ $WP_CORE_DIR/wp-content/plugins/versionpress/vendor/
  - cp plugins/versionpress/uninstall.php $WP_CORE_DIR/wp-content/plugins/versionpress/uninstall.php
  - cp plugins/versionpress/bootstrap.php $WP_CORE_DIR/wp-content/plugins/versionpress/bootstrap.php
  - cp plugins/versionpress/versionpress.php $WP_CORE_DIR/wp-content/plugins/versionpress/versionpress.php
  - cp plugins/versionpress/versionpress-functions.php $WP_CORE_DIR/wp-content/plugins/versionpress/versionpress-functions.php
  - ls -la $WP_CORE_DIR/wp-content/plugins/versionpress

  - cp -rip frontend/build/ $WP_CORE_DIR/wp-content/plugins/versionpress/admin/public/gui/

  - wp plugin activate --path=$WP_CORE_DIR versionpress
  - wp vp activate --yes --path=$WP_CORE_DIR
  - sudo sed -i -e "s,/var/www,$WP_CORE_DIR,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
before_script:

  - curl http://localhost/wordpress 
  
  - 'sed -i.bak -e "s/end2end-test-type: .*/end2end-test-type: wp-cli/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s/dbname: .*/dbname: $DB_NAME/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s/user: .*/user: $DB_USER/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s/password: .*/password: $DB_PASSWORD/" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s#path: .*#path: $WP_CORE_DIR#" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s#url: .*#url: http://localhost/wordpress#" plugins/versionpress/tests/test-config.yml'
  - 'sed -i.bak -e "s#firefox-binary: .*#firefox-binary: /usr/local/bin/firefox#" plugins/versionpress/tests/test-config.yml'

script: gulp --cwd plugins/versionpress/tests run-tests